name: water_social_media
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3

  firebase_core: ^0.4.4+3
  firebase_analytics: ^5.0.11
  cloud_firestore: ^0.13.5
  firebase_auth: ^0.16.0
  rxdart: ^0.21.0
  intl: ^0.16.1
  provider: ^4.1.2

  font_awesome_flutter: ^8.8.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
